name: ci

on: 
  workflow_dispatch:

jobs:
 lint:
  runs-on: ubuntu-latest
  steps:
  - name: Checkout
    uses: actions/checkout@v2
  - name: Set up Python 3.9
    uses: actions/setup-python@v2
    with:
     python-version: 3.9
  - run: pip install flake8
  - run: pip install mypy
  - run: flake8 run.py roop
  - run: mypy run.py roop
 test:
  strategy:
   matrix:
    os: [macos-latest, ubuntu-latest, windows-latest]
  runs-on: ${{ matrix.os }}
  steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
       python-version: 3.9
    - run: pip install -r requirements-headless.txt
    - name: Set up FFmpeg on macOS and Ubuntu
      if: matrix.os != 'windows-latest'
      run: |
        if [ "${{ matrix.os }}" == "macos-latest" ]; then
          brew install ffmpeg
        else
          sudo apt-get update
          sudo apt-get install ffmpeg
        fi
    - name: Set up FFmpeg on Windows
      if: matrix.os == 'windows-latest'
      run: |
        choco install ffmpeg
    - name: Run Python script
      run: |
        if: matrix.os != 'windows-latest'; then
          python run.py -s .github/examples/source.jpg -t .github/examples/target.mp4 -o .github/examples/output.mp4
          ffmpeg -i .github/examples/snapshot.mp4 -i .github/examples/output.mp4 -filter_complex psnr -f null -
        else
          python run.py -s .github\examples\source.jpg -t .github\examples\target.mp4 -o .github\examples\output.mp4
          ffmpeg -i .github\examples\snapshot.mp4 -i .github\examples\output.mp4 -filter_complex psnr -f null -
        fi

